name: Bench

on:
  workflow_dispatch:
inputs:
  name: 'h'
  type: number
  required: true

jobs:
  bench:
    name: Bench Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Preparations
        run: |
          sudo apt update
          sudo apt install -y python3
      
      - name: Execution
        run: |
          ulimit -t 21300
          python3 ./src/core/goldbach_conjecture.py '{{ inputs.h }}'



